# Generated by Django 4.0.3 on 2023-04-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_automobilevo_purchased_from_dealership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='purchased_from_dealership',
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
